version: "3.8"

services:  

  # elastic:    
  #   image: elasticsearch:${ELASTIC_VERSION}    
  #   env_file:
  #     - ./.env  

  # redis:    
  #   image: redis:${REDIS_VERSION}    
  #   env_file:
  #     - ./.env

  app:
    build:
      context: .
      dockerfile: Dockerfile     
    env_file:
      - ./.env    

  nginx:
    image: nginx:1.21.1
    depends_on:
      - app
    volumes:
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf  
    env_file:
      - ./.env
    ports:
      - "${NGINX_PORT}:80"



